# Generated by Django 5.0 on 2024-10-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_types',
            field=models.CharField(choices=[('leader', 'Cohort Leader'), ('deputy', 'Assistant Leader'), ('member', 'Cohort Member')], default='member', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='profile_picture',
            field=models.ImageField(upload_to='student_profile/'),
        ),
    ]
