# Generated by Django 5.0 on 2024-10-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_student_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_types',
        ),
        migrations.AddField(
            model_name='student_profile',
            name='student_types',
            field=models.CharField(choices=[('leader', 'Cohort Leader'), ('deputy', 'Assistant Leader'), ('member', 'Cohort Member')], default='member', max_length=100),
        ),
    ]
